from transformers import (
    T5ForConditionalGeneration,
    AutoTokenizer,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq
)
from datasets import load_dataset, Dataset, load_from_disk, concatenate_datasets
from huggingface_hub import login
import torch
import os

# ===== 1. Login =====
login(token="hf_")  # Replace with your token

# ===== 2. GPU Check =====
print(f"GPU:  {torch.cuda.get_device_name(0)}")
print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f}GB")

# ===== 3. Config =====
MODEL_NAME   = "google/byt5-base"
MAX_LEN      = 128
CACHE_DIR    = "./data/cached"
OUTPUT_DIR   = "./byt5-base-finetuned-v4"
FINAL_DIR    = "./byt5-base-finetuned-v4-final"
WIKI_AUG     = "./data/wiki_aug.jsonl"   # ← generated by augment_wiki.py

# Resume from checkpoint (set to None to start fresh)
# Example: "./byt5-base-finetuned-v4/checkpoint-20031"
RESUME_FROM  = None

# ===== 4. Tokenization Cache =====
def flatten(split):
    rows = []
    for example in split:
        for r, n in zip(example['raw'], example['norm']):
            rows.append({
                'raw':  r,
                'norm': n,
                'lang': example['lang']
            })
    return Dataset.from_list(rows)

def load_wiki_aug(path):
    """
    Load wiki_aug.jsonl and keep only the columns finetune needs.
    augment_wiki.py outputs: raw, norm, lang, corruption
    We drop 'corruption' here since it's not needed for training.
    """
    if not os.path.exists(path):
        print(f"⚠️  wiki_aug.jsonl not found at {path} — skipping augmentation")
        print(f"   Run: python data/augment_wiki.py")
        return None

    wiki = load_dataset('json', data_files=path, split='train')
    wiki = wiki.remove_columns(['corruption'])   # not needed for training
    print(f"✅ Loaded wiki_aug: {len(wiki)} pairs from {path}")
    return wiki

def get_tokenized_data(tokenizer, force_retokenize=False):
    train_cache = os.path.join(CACHE_DIR, "train_tokenized")
    val_cache   = os.path.join(CACHE_DIR, "val_tokenized")

    if os.path.exists(train_cache) and not force_retokenize:
        print("✅ Loading from cache (tokenization skipped)...")
        train_tok = load_from_disk(train_cache)
        val_tok   = load_from_disk(val_cache)
        print(f"   train: {len(train_tok)} samples")
        print(f"   val:   {len(val_tok)} samples")
        return train_tok, val_tok

    print("Tokenizing for first time (~5 min)...")
    dataset = load_dataset("weerayut/multilexnorm2026-dev-pub")

    train_flat = flatten(dataset['train'])
    val_flat   = flatten(dataset['validation'])
    print(f"  Original train: {len(train_flat)} samples")
    print(f"  val:            {len(val_flat)} samples")

    # ── Merge wiki augmentation ──────────────────────────────────────────────
    wiki_aug = load_wiki_aug(WIKI_AUG)
    if wiki_aug is not None:
        train_flat = concatenate_datasets([train_flat, wiki_aug])
        print(f"  Total train after augmentation: {len(train_flat)} samples")
    # ────────────────────────────────────────────────────────────────────────

    def preprocess(examples):
        inputs = tokenizer(
            examples['raw'],
            max_length=MAX_LEN,
            truncation=True,
            padding=False
        )
        labels = tokenizer(
            examples['norm'],
            max_length=MAX_LEN,
            truncation=True,
            padding=False
        )
        inputs['labels'] = labels['input_ids']
        return inputs

    print("  Tokenizing train...")
    train_tok = train_flat.map(
        preprocess,
        batched=True,
        remove_columns=['raw', 'norm', 'lang'],
    )
    print("  Tokenizing val...")
    val_tok = val_flat.map(
        preprocess,
        batched=True,
        remove_columns=['raw', 'norm', 'lang'],
    )

    os.makedirs(CACHE_DIR, exist_ok=True)
    train_tok.save_to_disk(train_cache)
    val_tok.save_to_disk(val_cache)
    print(f"✅ Cached to {CACHE_DIR} (next run will be instant!)")

    return train_tok, val_tok

# ===== 5. Model & Tokenizer =====
print(f"\nLoading {MODEL_NAME}...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = T5ForConditionalGeneration.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.bfloat16
)
model = model.to("cuda")
print("Model loaded!")

# ===== 6. Load Data =====
train_tok, val_tok = get_tokenized_data(tokenizer)

# ===== 7. Training Config =====
training_args = Seq2SeqTrainingArguments(
    output_dir=OUTPUT_DIR,

    # ByT5-base config
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    gradient_accumulation_steps=2,      # effective batch = 32
    gradient_checkpointing=True,

    # Training
    num_train_epochs=10,
    learning_rate=5e-4,
    bf16=True,

    # Evaluation & Saving
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=10,                # keep all epoch checkpoints
    load_best_model_at_end=False,       # turn off auto best-model selection

    # Generation
    predict_with_generate=True,
    generation_max_length=MAX_LEN,

    # Logging
    logging_steps=100,
    logging_dir="./runs/logs_base_v4",
    report_to="tensorboard",

    # Windows compatibility
    dataloader_num_workers=0,
    dataloader_pin_memory=False,
)

# ===== 8. Trainer =====
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=train_tok,
    eval_dataset=val_tok,
    processing_class=tokenizer,
    data_collator=DataCollatorForSeq2Seq(
        tokenizer,
        model=model,
        padding=True
    ),
)

# ===== 9. Train =====
print("\nStarting training!")
print(f"  Model:       ByT5-base (300M params)")
print(f"  Resume from: {RESUME_FROM}")

if RESUME_FROM and os.path.exists(RESUME_FROM):
    print(f"\n✅ Resuming from: {RESUME_FROM}")
    trainer.train(resume_from_checkpoint=RESUME_FROM)
else:
    print("\n⚠️  Starting fresh")
    trainer.train()

# ===== 10. Save =====
print("\nSaving model...")
model.save_pretrained(FINAL_DIR)
tokenizer.save_pretrained(FINAL_DIR)
print(f"Saved to {FINAL_DIR}")

# ===== 11. Quick Test =====
def normalize(word):
    inputs = tokenizer(word, return_tensors="pt").to("cuda")
    with torch.no_grad():
        outputs = model.generate(**inputs, max_new_tokens=32)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

print("\n=== Quick Test ===")
for w in ["tilfaeldigt", "u", "bcause", "lol", "ㄹㅇ"]:
    print(f"  '{w}' → '{normalize(w)}'")
